### ISSUE TITLE
Standard Part Operator and Differential Operator

### ISSUE THREAD

**Issue by ChristopherKing42** [bcrowell/inf#1]
Here's a suggestion for two new operators

Standard Part: You talk about this, but do no implement. Although pretty easy to "calculate in one's head", it would still be instructive to make it an actual operator.

Differential: Given an expression in terms of x, output the differential. For example, you could type in `differential[sin x, 7]`, which would yield the result of `sin (7 + dx) - sin (7)`, where `dx` is a user defined infinitesimal (and just `d` by default).

**Comment by bcrowell** [comment]
I don't have time to implement the standard part operator right now, but I would accept a patch. The idea for a differential operator seems outside the scope of this program, which isn't a computer algebra system.
